version: "3.7"
services:
  # Grafana
  grafana:
    image: grafana/grafana
    ports:
      - 8011:3000
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=some@passWord
      - GF_USERS_ALLOW_SIGN_UP=false
        #- GF_SERVER_ROOT_URL=/monitor
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 8012:9090
    restart: always
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
