global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: "node_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.16.57.1:9100"]
        labels:
          hostname: "Front-end-Server-01"
      - targets: ["172.16.57.6:9100"]
        labels:
          hostname: "Front-end-Server-02"
      - targets: ["172.16.58.2:9100"]
        labels:
          hostname: "Back-end-Server-01"
      - targets: ["172.16.58.3:9100"]
        labels:
          hostname: "Back-end-Server-02"
      - targets: ["172.16.58.5:9100"]
        labels:
          hostname: "Database-Server-01"
      - targets: ["172.16.58.6:9100"]
        labels:
          hostname: "Database-Server-02"
    scheme: http

  - job_name: "grafana"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - grafana:3000
    scheme: http

  - job_name: "mysql"
    static_configs:
      - targets: ["172.16.58.15:9104"]
        labels:
          hostname: "Online-payment_Database01_TST-hRDF"
      - targets: ["172.16.58.16:9104"]
        labels:
          hostname: "Online-payment_Database02_SRB-JTTJ"
