global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - node-exporter:9100
    scheme: http

  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - grafana:3000
    scheme: http

  - job_name: blackbox # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox:9115
  - job_name: blackbox-http # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://mpnfreshcoconut.com
        - https://lipeferry.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093


rule_files:
  - alert_rule.yml
